# Assignment 1_1 - 딥러닝 및 실습.
## 2020136052 컴퓨터공학부 - 박영서

### a_tensor_initialization.py

텐서 관련 기본적인 메서드 학습

In [2]:
import torch

t1 = torch.Tensor([1, 2, 3], device='cpu') # [1.. 2., 3.,] float 텐서 생성
print(t1.dtype) # 텐서의 데이터 타입 확인 (float32)
print(t1.device) # 텐서가 올려진 디바이스. 아까 CPU로 선언했다.
print(t1.requires_grad) # 자동미분 추적 여부. 디폴트는 false.
print(t1.size()) # 텐서의 차원 크기 반환. (torch.Size([3]))
print(t1.shape) # 둘은 같은 함수다.
t1_cpu = t1.cpu() # 이 텐서를 CPU 메모리에 있는 복사본으로 반환하는 것. 그러니까 새로운 텐서 객체다.
# 여기서 t1_cpu는 새로운 텐서 타입 인스턴스로 선언된 것.

t2 = torch.tensor([1, 2, 3]) # 팩토리 함수. 입력 타입을 자동으로 추론.
# [1, 2, 3]은 int32, [1., 2., 3.] -> float32 
# Tensor은 무조건 기본 타입(float32로 생성)
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

t2_cpu = t2.cpu()


print("#####")


a1=torch.tensor(1) # 스칼라(0차원) 텐서. ndim은 차원 수.
print(a1.shape, a1.ndim)

a2=torch.tensor([1]) # 길이 1의 1차원 벡터.
print(a2.shape, a2.ndim)

a3=torch.tensor([1, 2, 3, 4, 5])  
print(a3.shape, a3.ndim)
# 길이 5의 1차원 벡터

a4=torch.tensor([[1], [2], [3], [4], [5]])   
print(a4.shape, a4.ndim)
# 2차원 행렬(5행 1열)

a5 = torch.tensor([           # shape: torch.Size([3, 2]) 2차원 텐서
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]) - 3차원 텐서
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([               # shape: torch.Size([3, 1, 2, 1]) - 4차원 텐서
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([               # shape: torch.Size([3, 1, 2, 3]) - 4차원 텐서
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([          # shape: torch.Size([3, 1, 2, 3, 1]) - 5차원 텐서
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([             # shape: torch.Size([4, 5]) - 2차원 텐서    
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([             # shape: torch.Size([4, 4, 5]) - 3차원 텐서  
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
#####
torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


In [2]:
a11 = torch.tensor([                
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

ValueError: expected sequence of length 3 at dim 3 (got 2)

##### 오류가 발생하는 것이 정상. 모든 차원에서 크기가 일정해야 한다. 크기가 같았다고 가정하면 torch.size([4, 1, 2, 3]) 내지는 torch.size([4, 1, 2, 2])일 것.

## b_tensor_initialization_copy
### 추가 학습

In [6]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1) ## 이 경우 주어진 데이터는 float32 텐서로 변환한닫.
## Tensor로 텐서 인스턴스를 선언하면 원본 리스트와는 메모리를 공유하지 않음. -> 새로운 텐서를 생성.

l2 = [1, 2, 3]
t2 = torch.tensor(l2) ## 팩토리 함수기 때문에 인자 타입을 자동으로 추론한다. 따라서 텐서의 타입은 int64.
## 새로운 텐서 생성.

l3 = [1, 2, 3] # 리스트 생성
t3 = torch.as_tensor(l3)
## torch.as_tensor로 선언시 일부 경우에 따라 메모리를 공유하긴 하지만. 리스트는 메모리 공유가 불가하므로 새로운 텐서 인스턴스가 생성된다.

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

## 전부 결과값은 1, 2, 3으로 통일된다. torch.as.tensor로 선언한 l3이 있긴 하지만 리스트는 앞서 말했듯 메모리 공유가 안 되니까!


print("#######")


l4 = np.array([1, 2, 3]) 
t4 = torch.Tensor(l4)
## 넘파이 배열을 float32 텐서로 변환하여 새로운 텐서 생성. 메모리는 공유하지 않는다.

l5 = np.array([1, 2, 3])
t5 = torch.Tensor(l5)
## 넘파이 배열을 int32 텐서로 변환하여 새로운 텐서 생성. 상기와 같이 메모리는 공유하지 않는다.

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)
## 이 경우에는 넘파이 배열와 메모리를 공유해서 얉은 복사의 형식으로 이루어진다. 
## 따라서 원본 넘파이 배열 값이 변경되면 텐서 값도 같이 변경된다.

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

## 이 경우에는 numpy 배열과 값을 공유중인 t6의 값만 변동할 것.


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
#######
tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([100,   2,   3])


## c_tensor_initialization_constant_values
#### 텐서 생성 및 초기화 관련 여러가지 메소드들

In [13]:
import torch

## torch.ones() / torch.ones_like()

t1 = torch.ones(size=(5, )) # shape (5,)짜리, 1로 채워진 텐서 생성. 기본 타입은 float32.
t1_like = torch.ones_like(t1) ## t1와 같은 shape, 데이터 타입, 디바이스를 가지는 1로 태워진 텐서.

print(t1)
print(t1_like)

print("#####")

## torch.zeros(), torch.zeros_like()

t2 = torch.zeros(size=(6,)) # torch.ones()와 비슷하지만 이 쪽은 0으로 채운다.
t2_like = torch.zeros_like(input=t2) ## 이쪽도 0으로 채움.

print(t2)
print(t2_like)

print("######")

### torch.empty() / torch.empty_like()

t3 = torch.empty(size=(4,)) ## shape(4,)짜리 '초기화되지 않은' 텐서 생성.
t3_like = torch.empty_like(input=t3)

print(t3) ## 이 경우 메모리에 남아있는 임의의 값이나 0일수도 있는 것. 초기화되지 않은 거니까...
print(t3_like)

print("#####")

### torch.eye

t4 = torch.eye(n=3) # 3x3 단위행렬 생성. 대각선만 1인 행렬이다.
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
#####
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
######
tensor([1.0000e+00, 1.4013e-45, 0.0000e+00, 0.0000e+00])
tensor([-5.9517e+20,  2.0809e-42,  0.0000e+00,  0.0000e+00])
#####
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## d_tensor_initialization_random_values
#### 난수 / 수열 생성 메소드

In [20]:
import torch

t1 = torch.randint(low=10, high=20, size=(1, 2))
## shape가 (1, 2)인 텐서 생성, 여기서 내부 값은 10 이상 20 미만(정수)
print(t1)

t2 = torch.rand(size=(1, 3))
## 이 경우엔 [0.0, 1.0) 범위의 균일분포 난수. shape는 (1,3)
print(t2)

t3=torch.randn(size=(1, 3))
## 평균 0, 표준편차 1의 정규분포 난수. shape는 (1, 3)

t4 = torch.normal(mean = 10.0, std = 1.0, size = (3, 2))
## 평균 10.0, 표준편자 1.0의 정규분포 난수. shape=(3, 2)

t5 = torch.linspace(start = 0.0, end = 5.0, steps = 3)
## 0.0부터 5.0까지 균등 간격으로 3개 값 생성. [0.0, 5.0]
print(t5)

t6 = torch.arange(5)
# 0부터 4까지 정수 시퀀스 생성(range 유사)
# -> [0, 1, 2, 3, 4]
print(t6)

print("######")

# 여기서부터는 시드 난수 관련

torch.manual_seed(1729) # 시드 고정. 이러면 이후 난수값이 항상 동일하다. 물론 시드값을 기억하고 있다는 가정 하에...

random1 = torch.rand(2,3)
print(random1) # seed : 1729
random2 = torch.rand(2, 3)
print(random2) 

print()

torch.manual_seed(1729) # 같은 시드로 초기화

random3 = torch.rand(2, 3) # random1과 같은 값.
print(random3)
random4 = torch.rand(2, 3)
print(random4) # random2와 같은 값.

tensor([[17, 12]])
tensor([[0.0453, 0.5035, 0.9978]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
######
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


## e_tensor_type_conversion
#### 텐서 자료형 지정 및 변환 관련 메소드

In [27]:
import torch

a = torch.ones((2, 3))
print(a.dtype) ## 디폴트는 torch.float32다.

b = torch.ones((2, 3), dtype = torch.int16) ## dtype에 인자를 넣어 직접 자료형 지정 가능
print(b.dtype)

c = torch.rand((2, 30), dtype = torch.float64) * 20 ## 여기서 * 20은 스칼라 곱. 모든 원소에 20을 곱한다.
## [0.0, 1.0) -> [0.0, 20.0)
print(c)

### 여기서부터는 기존 텐서의 dtype을 변환하는 메소드들.

d = b.to(torch.int32)
print(d)

### 다양한 방식으로 데이터 타입 변환

## 생성시 지정
double_d = torch.ones(10, 2, dtype = torch.double)
# tensor([[1., 1.],
#         [1., 1.],
#         ...
#         [1., 1.]], dtype=torch.float64)
short_e = torch.tensor([[1, 2]], dtype = torch.short) 
print(short_e)

double_d = torch.zeros(10, 2).to(torch.double)
short_3 = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

print(double_d.dtype) # double = float64이므로 float64 출력
print(short_e.dtype) # torch.int16 -> short

## 연산시 dtype 브로드캐스팅

double_f = torch.rand(5, dtype=torch.double) #float64
short_g = double_f.to(torch.short)

print((double_f * short_g).dtype)
# float64 * int16 -> int16이 float64로 승격되면서 float64

torch.float32
torch.int16
tensor([[7.6611e+00, 1.8801e+01, 3.9405e+00, 1.0331e+01, 8.9673e+00, 4.9067e+00,
         9.1012e-03, 5.9629e+00, 1.1071e+01, 1.2571e+01, 1.6582e+01, 1.8456e+01,
         1.8698e-02, 8.1616e+00, 1.3194e+01, 7.2011e+00, 1.7360e+01, 4.2060e+00,
         1.2422e+01, 1.1559e+00, 6.5834e+00, 4.0778e+00, 1.4803e+01, 1.4196e+01,
         1.5153e+01, 1.8894e+01, 1.1434e+01, 1.9444e+01, 1.6538e+01, 8.7672e+00],
        [9.1008e+00, 1.9145e+01, 1.3189e+01, 3.0974e+00, 1.0855e+01, 1.7935e+01,
         8.3659e+00, 1.1664e+00, 1.2513e+01, 1.2812e+01, 8.9558e+00, 4.2822e+00,
         1.0630e+01, 9.2623e+00, 7.9516e+00, 1.6139e+01, 9.3634e+00, 4.7077e+00,
         2.2244e+00, 9.7197e+00, 1.8577e+01, 1.7785e+01, 9.5398e+00, 1.3406e+01,
         1.0089e+01, 3.0597e+00, 9.7314e+00, 1.5772e+01, 1.2001e+01, 1.4104e+01]],
       dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[1, 2]], dtype=torch.int16)
torch.float64
torch.int16
torch.float64

## f_tensor_operations
#### 파이토치 산술연산함수 VS 연산자

In [32]:
import torch

### 덧셈

t1 = torch.ones(size=(2, 3))
#[[1, 1, 1], [1, 1, 1]]
t2= torch.ones(size=(2, 3))

t3 = torch.add(t1, t2) # -> 함수 방식
t4 = t1 + t2 # -> 연산자 오버로딩
print(t3)
print(t4)

### 뺄셈
print("#####")

t5 = torch.sub(t1, t2)
t6 = t1 - t2

print(t5)
print(t6)

print("######")

### 곱셈

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

## 나눗셈
print("######")

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
#####
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
######
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
######
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


#### 모두 Element-Wise 방식--즉 같은 위치의 연산끼리 계산한다.
#### 기본적으로 shape가 같아야 하며, 다를 경우 브로드캐스팅 규칙이 적용된다. (작은 쪽의 텐서가 늘어남)

## g_tensor_operations_mm
#### 내적, 행렬곱, 배치 행렬곱

In [36]:
import torch

t1 = torch.dot(
    torch.tensor([2, 3]), # shape -> 2
    torch.tensor([2, 1]) # shape -> 2
)
print(t1, t1.size())
# t1 = 2 * 2 + 3 * 1 = 7, 내적값은 스칼라다.

print("######")
### 2D 행렬곱

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t3.size())

print("######")
### 3D 배치 행렬 곱셈

t5 = torch.randn(10, 3, 4)  # 10개의 (3x4) 행렬
t6 = torch.randn(10, 4, 5)  # 10개의 (4x5) 행렬
t7 = torch.bmm(t5, t6)
print(t7.size())
# 배치 10개 * (A의 행 × A의 열) @ (B의 행 × B의 열) → (A의 행 × B의 열)

tensor(7) torch.Size([])
######
tensor([[ 0.9053,  0.3740],
        [ 0.2944, -0.0980]]) torch.Size([3, 2])
######
torch.Size([10, 3, 5])


## h_tensor_operations_matmul
torch.matmul -> 차원에 따른 내적, 행렬곱, 3D 배치 행렬곱 동작 선택

In [42]:
import torch

## 벡터 x 벡터 -> 내적

t1 = torch.randn(3)
t2 = torch.randn(3) 
print(torch.matmul(t1, t2).size()) ## 어차피 스칼라니 0차원 스칼라 텐서...

## 행렬 x 벡터 -> 행렬곱

t3 = torch.rand(3, 4)
t4 = torch.rand(4)
print(torch.matmul(t3, t4).size()) ## 행렬 x 벡터시 벡터이므로 일차원 벡터 크기. 순서가 바뀌어도 알아서 matmul()이 보정해 줌

## 배치별 행렬곱

t5 = torch.randn(10, 3, 4) # shape [10, 3, 4]
t6 = torch.rand(4) # 스칼라
print(torch.matmul(t5, t6).size()) 
# 배치별 행렬곱. 마지막 두 차원만 행렬곱으로 계산하고 그 앞 차원은 전부 브로드캐스팅 차원

t7 = torch.randn(10, 3, 4)  # [10,3,4]
t8 = torch.randn(10, 4, 5)  # [10,4,5]
print(torch.matmul(t7, t8).size())  
# → torch.Size([10, 3, 5])

t9 = torch.randn(10, 3, 4)  # [10,3,4]
t10 = torch.randn(4, 5)     # [4,5]
print(torch.matmul(t9, t10).size())  
# → torch.Size([10, 3, 5]) $ (4, 5)가 (10, 4, 5)로 자동 브로드캐스트

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


## i_tensor_broadcasting
거듭제곱, 브로드캐스팅, 정규화

In [10]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("######")
### 2차원 - 1차원 브로드캐스팅

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print (t3 - t4)

print("######")
### 정규화

def normalize(x) :
    return x / 255 # 이미지 픽셀 값은 보통 0~255이므로... 0~1 사이의 실수로 바꾸는 정규화를 수행하는 것.

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size()) ## 단순 정규화이므로 크기는 유지.

print("######")
### 정규화 예제

t11 = torch.ones(4, 3, 2)               
t12 = t11 * torch.rand(3, 2)              
print(t12.shape)  # torch.Size([4,3,2])

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)               
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)               
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)               
t18 = torch.rand(3, 1, 1)                  
print((t17 + t18).size())

## 배치 차원 확장용으로 왼쪽에 1 하나 늘리는 건 아무런 문제 없음!
## 같은 차원이고, 원소가 다르면 (값이 1인 축만) 같은 값으로 확장.

print("######")

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

t25 = torch.empty(5, 2, 4, 1)
t26 = torch.empty(3, 1, 1)

# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match

## 축 확장은 어디까지나 1인 축만 가능한 것. 2 vs 3이라 아예 호환 불가!

print("######")
### 거듭제곱

t27 = torch.ones(4) * 5
print(t27)  # tensor([5.,5.,5.,5.])

t28 = torch.pow(t27, 2)  
print(t28)  # tensor([25.,25.,25.,25.])

exp = torch.arange(1., 5.) 
a = torch.arange(1., 5.)    # 지수
t29 = torch.pow(a, exp)
print(t29)  # tensor([1., 4., 27., 256.])

tensor([2., 4., 6.])
######
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
######
torch.Size([3, 28, 28])
######
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
######
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
######
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


## j_tensor_indexing_slicing
텐서 인덱싱 / 슬라이싱

In [3]:
import torch

## 기본 인덱싱

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1]) ## 두 번째 행
print(x[:, 1]) ## 모든 행의 두 번째 열
print(x[1, 2]) ## 1행 2열 원소 -> 2
print(x[:, -1]) ## 모든 행의 마지막 열. 이제 많이 쓰겠징


print("######")
### 슬라이싱 예시

print(x[1:]) ## 1행부터 끝까지 전부
print(x[1:, 3:]) ## 1행 ~ / 3열 ~

print("######")
### 부분선택 / 값 대입

y = torch.zeros((6, 6))

y[1:4, 2] = 1 # 1행에서 3열까지 2열 전부 1로
print(y)

print(y[1:4, 1:4]) ## 1행~3행, 1열~3열만 잘라서 출력

print("######")
### 부분 선택 / 값 대입

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)

print(z[:2])
# 0~1행 전부

print(z[1:, 1:3])
# 1~2행, 1~2열

print(z[:, 1:])
# 모든 행, 1~3열 → [[2,3,4],[3,4,5],[6,7,8]]

z[1:, 1:3] = 0
# 1~2행, 1~2열 부분을 0으로 바꾸기
print(z)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
######
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
######
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
######
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


## k_tensor_reshaping
텐서 셰이프 변환 관련 메소드

In [3]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)
t3 = t1.reshape(1, 6)

print(t2)
print(t3)

## view VS reshape :
## 원소 수가 같다는 전제 하에 둘다 셰이프만 바뀌지만, 메모리 처리 방식이 다름.
## view는 연속된 메모리가 필요하고, reshape는 필요하면 복사도 함.

t4 = torch.arange(8).view(2, 4)  # shape [2,4]
t5 = torch.arange(6).view(2, 3)  # shape [2,3]
print(t4)
print(t5)

print("#####")
### unsqueez -> 새 축 추가

t9 = torch.tensor([1, 2, 3])
t10 = t9.unsqueeze(1) # -> 1번 자리에 새 축 추가
print(t10)
t11 = torch.tensor([[1, 2, 3],
                    [4, 5, 6]])  # shape [2,3]
t12 = t11.unsqueeze(1)             # 1번 위치에 새 축 → [2,1,3]
print(t12, t12.shape)

print("######")
### flatten -> 1차원으로 펴기. 직관적이네

t13 = torch.tensor([[1, 2, 3],
                    [4, 5, 6]])  # shape [2,3]
t14 = t13.flatten()  # [6]
print(t14)  # [1,2,3,4,5,6]

t15 = torch.tensor([[[1, 2],[3, 4]],
                    [[5, 6],[7, 8]]])  # shape [2,2,2]
t16 = torch.flatten(t15)
t17 = torch.flatten(t15, start_dim=1)  ## 0번째 차원만 남기고 전부 평탄화.
## [1, 2, 3, 4], [5, 6, 7, 8]

print(t16)
print(t17)

print("######")
### 차원 순서 바꾸기 -> permute

t18 = torch.randn(2, 3, 5)                 # shape [2,3,5]
print(t18.shape)
print(torch.permute(t18, (2, 0, 1)).size())  # shape [5,2,3]
t19 = torch.tensor([[1, 2, 3],
                    [4, 5, 6]])
t20 = torch.permute(t19, dims=(0, 1))
t21 = torch.permute(t19, dims=(0, 1))
print(t20)
print(t21)

print("#######")
### transpose -> 전치

t22 = torch.transpose(t19, 0, 1) # (행, 열) 교환 -> [3, 2]
print(t22)

t23 = torch.t(t19) # 2D 전용 전치 -> [3, 2]
print(t23)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
#####
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
######
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
######
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
#######
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


## l_tensor_concat
여러 텐서를 지정한 축을 따라 이어붙이는

In [8]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim = 1)
print(t4.shape) # torch.Size([2, 6, 3])
### 1번 차원이 1+3+2 = 6으로 합쳐진 것.

print("######")

t5 = torch.arange(0, 3) # -> shape[3]
t6 = torch.arange(3, 8) # -> shape[5]

t7 = torch.cat((t5, t6), dim = 0)
print(t7.shape)
print(t7)

print("######")
### 2D 텐서끼리 이어붙이기 (dim = 0, dim = 1)

t8 = torch.arange(0, 6).reshape(2, 3)
t9 = torch.arange(6, 12).reshape(2, 3)

t10 = torch.cat((t8, t8), dim = 0)
print(t10.size()) # -> (4, 3)
t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # (2, 6)

print("######")
### 여러 개 한 번에

t12 = torch.arange(0, 6).reshape(2, 3)
t13 = torch.arange(6, 12).reshape(2, 3)
t14 = torch.arange(12, 18).reshape(2, 3)

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # [6, 3]

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # [2, 9]

print("######")
### 3D 텐서

t17 = torch.arange(0, 6).reshape(1, 2, 3)
t18 = torch.arange(6, 12).reshape(1, 2, 3)

t19 = torch.cat((t17, t18), dim = 0)
print(t19.size()) # [2, 2, 3]

t20 = torch.cat((t17, t18), dim = 1)
print(t20.size()) # [1, 4, 3]

t21 = torch.cat((t17, t18), dim = 2)
print(t21.size())  # [1, 2, 6]



torch.Size([2, 6, 3])
######
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
######
torch.Size([4, 3])
torch.Size([2, 6])
######
torch.Size([6, 3])
torch.Size([2, 9])
######
torch.Size([2, 2, 3])
torch.Size([1, 4, 3])
torch.Size([1, 2, 6])


## m_tensor_stacking.py
stack vs cat + unsqueeze

In [14]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])   # shape [2,3]

t3 = torch.stack([t1, t2], dim=0) 
# 새 축(dim = 0)을 만들고 그 아래에 두 텐서를 쌓는 것
# shape [2, 2, 3]

t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
# → 둘 다 [1,2,3이므로 cat하면 [2,2,3]
print(t3.shape, t3.equal(t4))  # torch.Size([2, 2, 3]) True 출력.

t5 = torch.stack([t1, t2], dim=1)  
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)

print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8)) ## 셋 다 true.
# 두 방식의 차이점이라면 stack은 새 축을 만들고 그 아래로 텐서를 쌓는 거라면,
# cat은 미리 새 축을 만든 뒤 거기다 이어붙이는 것. 어차피 결과는 같음.'

print("#######")
## 2D로 비교시

t9 = torch.arange(0, 3)
t10 = torch.arange(3, 6)

t11 = torch.stack((t9, t10), dim = 0)
print(t11)

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim = 0)
print(t11.equal(t12))

print("#####")
### 1D -> 2D

t13 = torch.stack((t9, t10), dim=1)  # 열을 추가한다는 감각으로
print(t13)
# [[0,3],
#  [1,4],
#  [2,5]]

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))  # True

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
#######
tensor([[0, 1, 2],
        [3, 4, 5]])
True
#####
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


## n_tensor_vstack_hstack.py
수직 - 수평으로 붙이기

In [15]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3) 
# [[1,2,3],
#  [4,5,6]]
# 수직으로 붙임
# 1D 벡터는 2D화

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
## 행이 3개, 열이 1개라는 감각으로

t6 = torch.vstack((t4, t5))
# [[1],[2],[3],[4],[5],[6]]
# shape [6,1]

t7 = torch.tensor([
  [[1,2,3],[4,5,6]],
  [[7,8,9],[10,11,12]]
])  

t8 = torch.tensor([
  [[13,14,15],[16,17,18]],
  [[19,20,21],[22,23,24]]
])  # [2,2,3]

t9 = torch.vstack([t7, t8])
## 3D 텐서에서는  깊게 생각할 것 없이 vstack = torch.cat(..., dim = 0) -> [4, 2, 3]

print("######")
### torch.hstack -> 수평 방향으로..

t10 = torch.tensor([1,2,3])
t11 = torch.tensor([4,5,6])
t12 = torch.hstack((t10, t11))
print(t12)
# [1,2,3,4,5,6]

## hstack에서 1D 벡터는 단순 이어붙이기.

t13 = torch.tensor([[1],[2],[3]])  # shape [3,1]
t14 = torch.tensor([[4],[5],[6]])  # shape [3,1]
t15 = torch.hstack((t13, t14))
print(t15)
# [[1,4],
#  [2,5],
#  [3,6]]

# 2D 세로벡터는 열이 늘어난다.(2D vstack() -> 행)

t16 = torch.tensor([
  [[1,2,3],[4,5,6]],
  [[7,8,9],[10,11,12]]
])  # [2,2,3]

t17 = torch.tensor([
  [[13,14,15],[16,17,18]],
  [[19,20,21],[22,23,24]]
])  # [2,2,3]

t18 = torch.hstack([t16, t17])
print(t18.shape)
### 3D 텐서는 dim = 1로 이어붙이기.

tensor([[1, 2, 3],
        [4, 5, 6]])
######
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 4, 3])


# 숙제 후기

_02_tensors에서는 텐서의 기본적인 메소드들을 학습하였다.  
텐서의 메소드들 자체는 직관적으로 짜여있어 사용하는 데에 문제는 없었지만, 2차원~3차원 행렬을 감각적으로 떠올리면서 이해하면서 진행하는 경우가 많아 어느정도 시간이 걸렸다.  
다만 브로드캐스팅으로 차원을 늘리거나 하는 것이 처음에는 직관적으로 이해가 가질 않아 생각보다 시간을 까먹었으며, 행렬 곱은 군생활 전 1학년때나 하던 거라 순간적으로 기억이 나질 않아 구글 등지에서 다시 한 번 찾아봐야 했다.   
아직도 순간순간 단순 텐서 크기와 차원이 헷갈릴 때가 있는데, 이건 계속 텐서에 익숙해지면 빨리 해결되리라 믿어야 할 것 같다.